name: Deploy Feed back Application 
run-name: Deploy Feed Back by ${{ github.actor }} and Event is ${{ github.event_name }}

on: 
  push:
    branches:
      - master
    
jobs:
  CI-Backend:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9' 

      - name: Install Requirements
        working-directory: ./src/feedback_backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test Linting 
        working-directory: ./src/feedback_backend
        run: |
          pip install flake8
          flake8 .

      - name: Testing 
        run: | 
          pip install pytest
          PYTHONPATH= ./src/. pytest ./tests


