name: CICD Workflow for Feedback Application 
run-name: CICD workflow Trigger by ${{ github.event_name}} by ${{ github.actor }}

on: 
  Pull-Request:
    branches: 
      - main
  push: 
    branches:
      - main
  
  Workflow_dispatch:

jobs:
  CI-Python:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: action/checkout@v3

      - name: set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt 
      
      - name: Run Tests
        working-directory: ./src/feedback_backend
        run: |
          pip install flake8 
          flake8 .

      - name: Run Unit Tests
        working-directory: ./src/feedback_backend
        run: |
          pip install pytest
          pytest ../../tests
  

  