name: CICD Workflow for Feedback Application 
run-name: CICD workflow Trigger by ${{ github.event_name}} by ${{ github.actor }}

on: 
  pull_request:
    branches: 
      - master
  push: 
    branches:
      - master
  
  workflow_dispatch:


jobs:
  CI-Python:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9' 

      - name: Install dependencies
        working-directory: ./src/feedback_backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt 
      
      - name: Run Linting Test
        working-directory: ./src/feedback_backend
        run: |
          pip install flake8 
          flake8 .

      - name: Run Unit Tests
        run: |
          pip install pytest
          PYTHONPATH=./src pytest 
           
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./src/feedback_backend 
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/feedbackapp:${{ github.run_id}}
             
  CI-Front:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./src/feedback_frontend
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/feedbackfrontend:${{ github.run_id}}

  Deploy:
    runs-on: ubuntu-latest
    needs: [CI-Python, CI-Front]
    steps:
      - name: checkout code
        uses: actions/checkout@v3 
      
      - name: Deploy to Server
        run: echo "Deploying to server..."